version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: image-rag-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: image_rag
      MYSQL_USER: image_rag
      MYSQL_PASSWORD: image_rag_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - image-rag-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  milvus:
    image: milvusdb/milvus:v2.5.14
    container_name: image-rag-milvus
    command: milvus run standalone
    security_opt:
      - seccomp:unconfined
    environment:
      - ETCD_USE_EMBED=true  # 启用内置Etcd
      - ETCD_DATA_DIR=/var/lib/milvus/etcd  # 内置Etcd数据目录
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml  # 内置Etcd配置路径
      - COMMON_STORAGETYPE=local  # 使用本地存储（替代MinIO）
    volumes:
      - ./volumes/milvus:/var/lib/milvus  # 本地数据持久化
      - ./milvus/embedEtcd.yaml:/milvus/configs/embedEtcd.yaml  # 内置Etcd配置
      - ./milvus/user.yaml:/milvus/configs/user.yaml  # 用户自定义配置
    ports:
      - "19530:19530"  # Milvus服务端口
      - "9091:9091"    # 健康检查端口
      - "2379:2379"    # 内置Etcd客户端端口
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s

volumes:
  mysql_data:
  
networks:
  image-rag-network:
    driver: bridge