linters-settings:
  goimports:
    local-prefixes: image-rag-backend
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  misspell:
    locale: US
  lll:
    line-length: 120
  gci:
    sections:
      - standard
      - default
      - prefix(image-rag-backend)

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
    - path: internal/models/
      linters:
        - lll